### ISSUE TITLE
Highlighting (snippets)

### ISSUE THREAD

**Issue by jbothma** [stadt-karlsruhe/ckanext-extractor#12]
Have you seen any need for showing search match snippets?

We'd like to show search match relevance. Snippets from the usual indexed fields as well as the full text field would probably be very useful for us. Just thought I'd raise it here, although it should probably be done as a separate plugin.

One way of implementing it might just be to configure solr to store the fulltext field and enable highlighting. And then have the package search API include the highlighting results in the response somehow.

I'm keen to hear your thoughts.

**Comment by torfsen** [comment]
Highlighting would indeed be a nice addition, both for the metadata stored by CKAN itself and for that provided by ckanext-extractor.

AFAIK, it would require the following things:

1. Solr needs to be appropriately configured so that it has enough information to create the highlighting. If I understand [Solr's highlighting docs](https://lucene.apache.org/solr/guide/6_6/highlighting.html) correctly, then a basic requirement would be that the texts are actually stored in the Solr index. We currently do this for CKAN's original fields, but not for the metadata collected by ckanext-extractor. The latter would be easy to change, but would obviously increase the index size. For more advanced (and faster) highlighting, one would need to store even more information in the Solr index, e.g. `termVectors`.
2. We would need to tell Solr that we want highlighting. That can be configured globally in `solrconfig.xml`, or it can be configured separately for each query. The latter would probably mean that we need to change/override the `package_search` API function, since it currently doesn't accept the highlighting-related Solr parameters.
3. We would need to pass the highlighting information obtained from Solr back to the caller of `package_search`. Again, this probably implies changing or overriding `package_search`.
4. We would need to display the highlighting information. Changing/overriding the appropriate template(s) is probably enough for that.

All of these things could be done in an extension. However, this would mean to override `package_search` in that extension, and I'm not sure whether this is a good idea given that this is a rather important part of CKAN core -- keeping the extension's implementation up-to-date with the changes in CKAN might be too much of an effort.

However, a plugin would be a very good way to prototype this idea. I don't think ckanext-extractor is a good place for this kind of functionality, though. However, [ckanext-discovery](https://github.com/stadt-karlsruhe/ckanext-discovery) already provides several search-related plugins and a highlighting plugin would fit in there nicely. We don't have the resources to work on this for the foreseeable future, but PRs are always welcome.

I'm closing this issue since the related work wouldn't be part of ckanext-extractor. Feel free to open a new ticket over at [ckanext-discovery](https://github.com/stadt-karlsruhe/ckanext-discovery) or at [CKAN's ideas and roadmap](https://github.com/ckan/ideas-and-roadmap).

**Comment by jbothma** [comment]
Thanks for the great feedback. Really helpful.
